# Generated by Django 5.0.2 on 2024-02-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aether', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parent', to='Aether.comment'),
        ),
    ]
