# Generated by Django 5.0.2 on 2024-02-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aether', '0002_comment_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=12100.09),
        ),
    ]
