# Generated by Django 5.0.2 on 2024-02-27 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aether', '0003_alter_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aether.account'),
        ),
    ]
