# Generated by Django 5.0.2 on 2024-03-16 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aether', '0006_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aether.account'),
        ),
    ]
