# Generated by Django 5.0.2 on 2024-04-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aether', '0009_alter_review_product_remove_productimage_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
